apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: secrets-manager
spec:
  params:
    - name: secrets-manager-apikey
      description: api key property
    - name: secrets-manager-endpoint
      description: ibmcloud endpoint
  steps:
    - name: secrets-manager-test
      image: icr.io/continuous-delivery/pipeline/pipeline-base-image
      env:
        - name: SECRETS_MANAGER_APIKEY
          value: $(inputs.params.secrets-manager-apikey)
        - name: SECRETS_MANAGER_ENDPOINT
          value: $(inputs.params.secrets-manager-endpoint)
      command: ["bash", "-c"]
      args:
        - |
          #!/usr/bin/env bash
          echo "Secrets Manager Test"
          echo "================"
          echo "env: ${SECRETS_MANAGER_ENDPOINT}"
          ibmcloud config --check-version=false
          ibmcloud login -a ${SECRETS_MANAGER_ENDPOINT} --apikey ${SECRETS_MANAGER_APIKEY} --no-region
